[package]
name = "actix-cocktail-api"
version = "0.1.0"
authors = ["Mark Smith <judy@judy.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
mongodb = "1.2.1"
serde = "1.0"
serde_json = "1.0.64"
futures = "0.3.14"
chrono = { version = "0.4.19", features = ["serde"] }
tokio = "0.2.25"